# Generated by Django 3.1.7 on 2021-04-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='Производитель')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('product_type', models.CharField(db_index=True, max_length=20, verbose_name='Тип продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_amount', models.CharField(max_length=15, verbose_name='Кол-во памяти')),
                ('memory_type', models.CharField(max_length=15, verbose_name='Тип памяти')),
                ('memory_frequency', models.CharField(max_length=15, verbose_name='Частота памяти')),
                ('bus_width', models.CharField(max_length=15, verbose_name='Разрядность шины')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videocards', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal', models.CharField(max_length=15, verbose_name='Диагональ')),
                ('resolution', models.CharField(max_length=15, verbose_name='Разрешение экрана')),
                ('matrix_type', models.CharField(max_length=15, verbose_name='Тип матрицы')),
                ('features', models.CharField(max_length=100, verbose_name='Особенности')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_speed', models.CharField(max_length=15, verbose_name='Частота процессора')),
                ('number_of_cores', models.IntegerField(null=True, verbose_name='Количество ядер')),
                ('soket', models.CharField(max_length=15, verbose_name='Сокет')),
                ('family', models.CharField(max_length=15, verbose_name='Семейство процессора')),
                ('generation', models.CharField(max_length=15, verbose_name='Поколение процессора')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpus', to='catalog.product')),
            ],
        ),
    ]
